### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by flukeout** [flukeout/thimble-home#1]
**Details Bar**
- [ ] Sort out fonts for the title bar

**Homepage**
- [ ] Polish up the pencil animation
  - [ ] Quicker stroke on the line drawing animation

**404**
Seems all good
